image: debian:stretch-slim

before_script:

  - apt update -y
  - apt install php openssh-client wget ca-certificates php-curl php-xml php-mbstring git zip unzip -y
  - >
    EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)";
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";
    ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")";
    if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ];
    then >&2 echo 'ERROR: Invalid installer signature';
    rm composer-setup.php;
    exit 1;
    fi;
    php composer-setup.php --quiet;
    rm composer-setup.php;
  - mv composer.phar /usr/local/bin/composer
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_test:

  stage: deploy
  script:
#    - rm vendor/ -r
    - composer update
    - ssh-add <(echo "$TEST_SSH_PRIVATE_KEY")
    - scp -P1022 -r ./* egressos@egressos.fabricadesoftware.ifc.edu.br:/var/www/egressos


  environment:
    name: test
    url: https://egressos.fabricadesoftware.ifc.edu.br
  only:
    - Producao